import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import {cn} from "@/lib/utils";
import {Inter} from "next/font/google";
import {Providers} from "@/components/Providers";
import {SessionProvider} from "@/components/SessionProvider";
import {getServerSession} from "next-auth";
import {authOptions} from "@/lib/authOptions";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Milo | Ask Me Anything",
    description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    const session = await getServerSession(authOptions)
    return (
        <html lang="en">
        <body
            className={cn(inter.className, "min-h-screen antialiased")}
        >
        <Providers>
            <SessionProvider session={session}>
                <main className="h-screen dark text-foreground bg-background">
                    {children}
                </main>
            </SessionProvider>
        </Providers>
        </body>
        </html>
    );
}
